
class Commons {

  static const List<Map<String, String>> languages = [
    {'code': 'ta', 'name': 'Tamil'},
    {'code': 'es', 'name': 'Spanish'},
    {'code': 'fr', 'name': 'French'},
    {'code': 'de', 'name': 'German'},
    {'code': 'ja', 'name': 'Japanese'},
    {'code': 'ko', 'name': 'Korean'},
    {'code': 'zh', 'name': 'Chinese'},
    {'code': 'hi', 'name': 'Hindi'},
    {'code': 'ar', 'name': 'Arabic'},
    {'code': 'ru', 'name': 'Russian'},
    {'code': 'pt', 'name': 'Portuguese'},
    {'code': 'it', 'name': 'Italian'},
    {'code': 'nl', 'name': 'Dutch'},
    {'code': 'tr', 'name': 'Turkish'},
    {'code': 'pl', 'name': 'Polish'},
    {'code': 'sv', 'name': 'Swedish'},
    {'code': 'th', 'name': 'Thai'},
    {'code': 'id', 'name': 'Indonesian'},
    {'code': 'vi', 'name': 'Vietnamese'},
    {'code': 'ms', 'name': 'Malay'},
    {'code': 'fil', 'name': 'Filipino'},
    {'code': 'bn', 'name': 'Bengali'},
    {'code': 'he', 'name': 'Hebrew'},
    {'code': 'ur', 'name': 'Urdu'},
    {'code': 'fa', 'name': 'Persian'},
    {'code': 'el', 'name': 'Greek'},
    {'code': 'hu', 'name': 'Hungarian'},
    {'code': 'cs', 'name': 'Czech'},
    {'code': 'ro', 'name': 'Romanian'},
    {'code': 'da', 'name': 'Danish'},
    {'code': 'no', 'name': 'Norwegian'},
    {'code': 'fi', 'name': 'Finnish'},
    {'code': 'bg', 'name': 'Bulgarian'},
    {'code': 'sk', 'name': 'Slovak'},
    {'code': 'sl', 'name': 'Slovenian'},
    {'code': 'hr', 'name': 'Croatian'},
    {'code': 'sq', 'name': 'Albanian'},
    {'code': 'sr', 'name': 'Serbian'},
    {'code': 'mk', 'name': 'Macedonian'},
    {'code': 'et', 'name': 'Estonian'},
    {'code': 'lv', 'name': 'Latvian'},
    {'code': 'lt', 'name': 'Lithuanian'},
    {'code': 'ka', 'name': 'Georgian'},
    {'code': 'hy', 'name': 'Armenian'},
    {'code': 'az', 'name': 'Azerbaijani'},
    {'code': 'uz', 'name': 'Uzbek'},
    {'code': 'kk', 'name': 'Kazakh'},
    {'code': 'ky', 'name': 'Kyrgyz'},
    {'code': 'tk', 'name': 'Turkmen'},
    {'code': 'mn', 'name': 'Mongolian'},
    {'code': 'ne', 'name': 'Nepali'},
    {'code': 'si', 'name': 'Sinhala'},
    {'code': 'my', 'name': 'Burmese'},
    {'code': 'km', 'name': 'Khmer'},
    {'code': 'lo', 'name': 'Lao'},
  ];
}